### ISSUE TITLE
Change file sharing to Socket-based IPC

### ISSUE THREAD

**Issue by timashana** [ncp-hash/public-phash#1]
The IPC requires 3 communications:

1.  Server shares public key pu with Client
2. Server shares vector of encrypted betas enc_betas with client
3. Client shares encryption of hash enc_sum_res with server

Currently, all communication is done through shared files: pubkey.txt for step 1) and ciphertext.txt fro steps 2) and 3). File sharing causes race condition and uncertain results which are temporarily fixed with sleep() statements in both Server and Client programs.

TODO:
Implement TCP/IP-based inter-process communication (with synchronization) and replace file sharing.

**Comment by promethium146** [comment]
Wow, this was finished a while ago! See commit 850e730b8b68f58aea1d1f9d95ee3d39818e8290 to on master branch.
